<?php

/**
 * Implements hook_block_info().
 */
function tastybackend_demo_blocks_block_info() {
  $blocks['tastybackend_demo_blocks_login'] = array(
    'info' => t('Tasty Backend Demo Login Info'),
    'weight' => -9,
    'status' => 1,
    'region' => 'sidebar_first',
  );
  $blocks['tastybackend_demo_blocks_profile'] = array(
    'info' => t('Tasty Backend Demo Profile Info'),
    'weight' => -10,
    'status' => 1,
    'region' => 'sidebar_first',
  );
  $blocks['tastybackend_demo_blocks_dc'] = array(
    'info' => t('Tasty Backend Demo Delicious Creative link'),
    'weight' => -10,
    'status' => 1,
    'region' => 'footer',
  );

  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function tastybackend_demo_blocks_block_view($delta = '') {
  
  $block = array();
  
  if ($delta == 'tastybackend_demo_blocks_login') {
    $content = '<p>To log in and experience the Tasty Backend firsthand, use the account info below:</p>';
    $content .= '<p>U: demo<br>P: demo</p>';
    $block['subject'] = t('Login Info');
    $block['content'] = $content;
  }
  if ($delta == 'tastybackend_demo_blocks_profile') {
    $block['subject'] = t('Get the Profile');
    $block['content'] = '<p>The Tasty Backend Standard installation profile is currently in development, but you can <a href="https://github.com/jenitehan/tasty_backend">grab it on GitHub</a>.</p>';
  }
  if ($delta == 'tastybackend_demo_blocks_dc') {
    $block['content'] = 'Made by <a href="http://www.deliciouscreative.com">Delicious Creative</a>';
  }
  
  return $block;
  
}